favicon: null
name: 'Architexture '
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4659498
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#000000'
    - '#DFDFDF'
    - '#BBBCC0'
    - '#FFFFFF'
    - '#007AFF'
  rhythmicContrast: 0.5322581
typography_spectrum: 0.1111111
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4802867
analytics:
  twitter: null
  google: null
  facebook: null
