name: 'Architexture '
favicon: null
layout_spectrum: 0.7013454213738441
typography_spectrum: 0.8527146682608873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7089067935012281
  lightness: 0.8363006869331002
  saturation: 0.6965478130150586
  rhythmicContrast: 0.9843948294874281
purpose: []
