favicon: null
name: 'Architexture '
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#000000'
    - '#DFDFDF'
    - '#BBBCC0'
    - '#FFFFFF'
    - '#007AFF'
  rhythmicContrast: 0
typography_spectrum: 0.4444444
layout_spectrum: 0.9820789
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
