favicon: null
name: 'Architexture '
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.5
  rhythmicContrast: 0.5
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#BFBFBF'
    - '#7F7F7F'
    - '#404040'
  lightness: 0.75
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.781362
analytics:
  twitter: null
  google: null
  facebook: null
